server:
  port: 8222

eureka:
  instance:
    hostname: bankatii-gateway-crypto.onrender.com
  client:
    serviceUrl:
      defaultZone:
        ${EUREKA_HOST:https://bankatii-discovery.onrender.com/eureka/}
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false